---

- name: NGINX | Install NGINX
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: NGINX | Create general config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: reload-nginx

- name: Lighthouse | install dependencies
  apt:
    name: git
    state: latest

- name: Lighthouse | Copy from git
  git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir  }}"
  notify: reload-nginx

- name: Lighthouse | Create lighthouse config
  template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: reload-nginx